//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngishMotherFucker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings___Копировать {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings___Копировать() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngishMotherFucker.Resources.Strings.Strings - Копировать", typeof(Strings___Копировать).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание на английском.
        /// </summary>
        public static string Edit_Word_Definition_En_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Definition_En_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определение (англ.).
        /// </summary>
        public static string Edit_Word_Definition_En_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Definition_En_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание на русском.
        /// </summary>
        public static string Edit_Word_Definition_Ru_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Definition_Ru_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определение (рус.).
        /// </summary>
        public static string Edit_Word_Definition_Ru_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Definition_Ru_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Edit_Word_Delete_Button {
            get {
                return ResourceManager.GetString("Edit_Word_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например, существительное.
        /// </summary>
        public static string Edit_Word_Part_Of_Speech_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Part_Of_Speech_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часть речи.
        /// </summary>
        public static string Edit_Word_Part_Of_Speech_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Part_Of_Speech_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Edit_Word_Save_Button {
            get {
                return ResourceManager.GetString("Edit_Word_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория или тема.
        /// </summary>
        public static string Edit_Word_Topic_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Topic_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема.
        /// </summary>
        public static string Edit_Word_Topic_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Topic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например, [æpl].
        /// </summary>
        public static string Edit_Word_Transcription_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Transcription_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транскрипция.
        /// </summary>
        public static string Edit_Word_Transcription_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Transcription_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите перевод.
        /// </summary>
        public static string Edit_Word_Translation_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Translation_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод.
        /// </summary>
        public static string Edit_Word_Translation_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Translation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примеры.
        /// </summary>
        public static string Edit_Word_Usage_Example_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Usage_Example_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примеры использования.
        /// </summary>
        public static string Edit_Word_Usage_Example_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Usage_Example_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите слово.
        /// </summary>
        public static string Edit_Word_Word_Placeholder {
            get {
                return ResourceManager.GetString("Edit_Word_Word_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово.
        /// </summary>
        public static string Edit_Word_Word_Title {
            get {
                return ResourceManager.GetString("Edit_Word_Word_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить слово.
        /// </summary>
        public static string Main_Page_Add_New_Word_Button {
            get {
                return ResourceManager.GetString("Main_Page_Add_New_Word_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Main_Page_Search_Placeholder {
            get {
                return ResourceManager.GetString("Main_Page_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренажер.
        /// </summary>
        public static string Main_Page_Start_Training_Button {
            get {
                return ResourceManager.GetString("Main_Page_Start_Training_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных:.
        /// </summary>
        public static string Settings_Database_Title {
            get {
                return ResourceManager.GetString("Settings_Database_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать базу.
        /// </summary>
        public static string Settings_Export_Database {
            get {
                return ResourceManager.GetString("Settings_Export_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать базу.
        /// </summary>
        public static string Settings_Import_Database {
            get {
                return ResourceManager.GetString("Settings_Import_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество вопросов: .
        /// </summary>
        public static string Settings_Training_Questions_Amount {
            get {
                return ResourceManager.GetString("Settings_Training_Questions_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принцип формирования вопросов:.
        /// </summary>
        public static string Settings_Training_Questions_Forming_Principle {
            get {
                return ResourceManager.GetString("Settings_Training_Questions_Forming_Principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки тренажера:.
        /// </summary>
        public static string Settings_Training_Title {
            get {
                return ResourceManager.GetString("Settings_Training_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тут будет краткое описание....
        /// </summary>
        public static string Training_Description {
            get {
                return ResourceManager.GetString("Training_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принцип:.
        /// </summary>
        public static string Training_Principle {
            get {
                return ResourceManager.GetString("Training_Principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать тренировку.
        /// </summary>
        public static string Training_Start_Training {
            get {
                return ResourceManager.GetString("Training_Start_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переведи слово: .
        /// </summary>
        public static string Training_Task_Translate {
            get {
                return ResourceManager.GetString("Training_Task_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в тренажёр!.
        /// </summary>
        public static string Training_Welcome_Message {
            get {
                return ResourceManager.GetString("Training_Welcome_Message", resourceCulture);
            }
        }
    }
}
